version: '3'

services:
  deephaven-plugins-docs:
    container_name: deephaven-plugins
    build:
      dockerfile: ./Dockerfile
      pull: true # We need to always pull the latest server image used in the Dockerfile
    ports:
      - '${DEEPHAVEN_SNAPSHOT_PORT:-10090}:10000'
    volumes:
      - /app.d/
    environment:
      - START_OPTS=-Xmx4g -DAuthHandlers=io.deephaven.auth.AnonymousAuthenticationHandler -Ddeephaven.console.type=python -Ddeephaven.application.dir=./app.d

  deephaven-plugins-docs-extractor:
    image: ghcr.io/deephaven/salmon-extractor
    container_name: deephaven-plugins-docs-extractor
    command:
      [
        'sh',
        '-c',
        'node extract.cjs --directory /extract/plotly-express --output /results/plotly-express; node extract.cjs --directory /extract/ui --output /results/ui',
      ]
    volumes:
      - ./plugins/ui/docs:/extract/ui
      - ./plugins/plotly-express/docs:/extract/plotly-express
      # exclude doc build directories by overriding with empty volumes
      # We could extract from the build directories, but we need to output the snapshots to the build directory itself for Salmon to pick up...
      - /extract/plotly-express/build/
      - /extract/ui/build/
      - ./docker/build/test-sets:/results # Output to a temporary build directory

  deephaven-plugins-docs-snapshotter:
    image: ghcr.io/deephaven/salmon-snapshotter
    depends_on:
      deephaven-plugins-docs:
        condition: service_healthy
      deephaven-plugins-docs-extractor:
        condition: service_completed_successfully
    environment:
      HOST_URL: 'http://deephaven-plugins-docs:10000'
    command:
      [
        'sh',
        '-c',
        'node snapshot.cjs --directory /test-sets/plotly-express --output /results/plotly-express; node snapshot.cjs --directory /test-sets/ui --output /results/ui',
      ]
    volumes:
      - ./docker/build/test-sets:/test-sets
      # Map all the results back to the snapshots directory for those docs
      - ./plugins/ui/docs/snapshots:/results/ui
      - ./plugins/plotly-express/docs/snapshots:/results/plotly-express
