/**
 * Generate per-block Python fixture files so the docs examples become
 * importable app.d panels.
 *
 * Each non-skip `Block` becomes its own `<outDir>/block_<md5>.py` file. The
 * block's code runs inside a uniquely-named function so its locals stay
 * isolated; only the names listed in `order=` are hoisted into module scope,
 * and each hoisted name is prefixed with the first 8 hex chars of the block
 * md5 to avoid collisions across pages that reuse names like `primary`,
 * `ohlc`, `stocks`, etc.
 *
 * Output layout:
 *
 *     <outDir>/
 *       block_<md5_1>.py
 *       block_<md5_2>.py
 *       ...
 *       tests.app           # Deephaven app.d manifest
 *
 * The output directory is treated as a build artifact and should be
 * gitignored.
 */
import {
  mkdirSync,
  writeFileSync,
  existsSync,
  readdirSync,
  unlinkSync,
} from 'node:fs';
import { join } from 'node:path';
import type { Block } from './extract.js';

export interface GenerateAppdResult {
  blockCount: number;
  manifestPath: string;
  /** md5 → prefix used to mangle that block's exported names. */
  prefixMap: Map<string, string>;
}

/**
 * Compute the per-block prefix used both as the function name and as the
 * leading segment of every exported global. We MUST start with a letter
 * because Python identifiers can't begin with a digit (md5 hashes very
 * often do). `b` for "block".
 *
 * Single source of truth — fixtures, the manifest, the prefix-map, and
 * the spec's `mangle()` all read this.
 */
export function blockPrefix(md5: string): string {
  return `b${md5.slice(0, 8)}`;
}

/**
 * Build the body of a single per-block fixture file.
 * Exposed for unit tests.
 */
export function renderBlockFile(block: Block, page: string): string {
  // `prefix` is what user-visible exported globals get tagged with — it
  // must be a valid Python identifier (i.e. start with a letter), so it
  // carries the leading `b` from `blockPrefix()`. The internal function
  // name and locals dict are private (`_block_<md5_8>`) and don't need
  // the `b` since the leading underscore already makes them valid.
  const md5_8 = block.md5.slice(0, 8);
  const prefix = blockPrefix(block.md5);
  const funcName = `_block_${md5_8}`;
  const localsVar = `_block_${md5_8}_locals`;
  const orderTxt = block.order.length > 0 ? block.order.join(',') : '';

  // Indent each line of the original code by four spaces so it sits inside
  // the wrapper function. Preserve blank lines but don't leave trailing
  // whitespace on them.
  const body = block.code
    .replace(/\s+$/g, '')
    .split('\n')
    .map(line => (line.length === 0 ? '' : '    ' + line))
    .join('\n');

  const lines: string[] = [
    `# Auto-generated by @deephaven/image-snapshotter. Do not edit.`,
    `# Source: docs/${page}`,
    `# Block md5: ${block.md5}`,
    `# order=${orderTxt}`,
    ``,
    ``,
    `def ${funcName}():`,
    body,
    `    return locals()`,
    ``,
    ``,
    `${localsVar} = ${funcName}()`,
    ``,
  ];
  for (const name of block.order) {
    lines.push(`${prefix}_${name} = ${localsVar}[${JSON.stringify(name)}]`);
  }
  // Trailing newline so the file ends cleanly.
  lines.push('');
  return lines.join('\n');
}

/**
 * Build the app.d manifest body listing every block fixture file.
 * Exposed for unit tests.
 */
export function renderManifest(
  blockFileNames: string[],
  appId: string = process.env.SNAPSHOTTER_APP_ID ?? 'docs.examples',
  appName: string = process.env.SNAPSHOTTER_APP_NAME ?? 'Docs Examples',
): string {
  const lines: string[] = [
    `type=script`,
    `scriptType=python`,
    `enabled=true`,
    `id=${appId}`,
    `name=${appName}`,
  ];
  blockFileNames.forEach((name, idx) => {
    lines.push(`file_${idx}=${name}`);
  });
  return lines.join('\n') + '\n';
}

/**
 * Emit one `block_<md5>.py` per non-skip block plus a `tests.app` manifest
 * into `outDir`. Stale `block_*.py` files (e.g. blocks that were removed
 * from docs) are cleaned up. Returns counts plus the md5→prefix map so
 * callers can translate display names to mangled global names.
 */
export function generateAppdFixtures(
  blocks: Block[],
  outDir: string,
): GenerateAppdResult {
  mkdirSync(outDir, { recursive: true });

  const nonSkip = blocks.filter(b => !b.skip);

  // Dedupe by md5 — identical code in different pages would otherwise
  // collide on filename anyway, and the prefix is keyed by md5 so they'd
  // get the same mangled names regardless.
  const seen = new Map<string, Block>();
  for (const b of nonSkip) {
    if (!seen.has(b.md5)) seen.set(b.md5, b);
  }

  const prefixMap = new Map<string, string>();
  const writtenFiles = new Set<string>();
  const blockFileNames: string[] = [];

  // Stable file ordering by md5 so the manifest diffs cleanly.
  const orderedBlocks = Array.from(seen.values()).sort((a, b) =>
    a.md5.localeCompare(b.md5),
  );

  for (const block of orderedBlocks) {
    const prefix = blockPrefix(block.md5);
    prefixMap.set(block.md5, prefix);
    const fileName = `block_${block.md5}.py`;
    const filePath = join(outDir, fileName);
    writeFileSync(filePath, renderBlockFile(block, block.page), 'utf8');
    writtenFiles.add(fileName);
    blockFileNames.push(fileName);
  }

  const manifestPath = join(outDir, 'tests.app');
  writeFileSync(manifestPath, renderManifest(blockFileNames), 'utf8');
  writtenFiles.add('tests.app');

  // Sweep stale files left over from previous runs (renamed/removed blocks).
  if (existsSync(outDir)) {
    for (const f of readdirSync(outDir)) {
      if (!f.startsWith('block_') || !f.endsWith('.py')) {
        if (f !== 'tests.app') continue;
      }
      if (!writtenFiles.has(f)) {
        try {
          unlinkSync(join(outDir, f));
        } catch {
          // ignore
        }
      }
    }
  }

  return {
    blockCount: orderedBlocks.length,
    manifestPath,
    prefixMap,
  };
}

// ---------------------------------------------------------------------------
// Legacy per-page fixture writer.
//
// Older flows (local dev) imported `generateFixtures` to write one .py per
// docs page. Kept here as a thin compatibility shim that delegates to the
// new per-block generator so existing callers don't break.
// ---------------------------------------------------------------------------

export interface FixtureWrite {
  page: string;
  pyPath: string;
  blockCount: number;
}

export function generateFixtures(blocks: Block[], outDir: string): FixtureWrite[] {
  const res = generateAppdFixtures(blocks, outDir);
  // Roll up per-page counts for the legacy return shape.
  const counts = new Map<string, number>();
  for (const b of blocks) {
    if (b.skip) continue;
    counts.set(b.page, (counts.get(b.page) ?? 0) + 1);
  }
  void res;
  return Array.from(counts.entries()).map(([page, blockCount]) => ({
    page,
    pyPath: join(outDir, 'tests.app'),
    blockCount,
  }));
}
