from __future__ import annotations
from typing import Any
from inspect import signature
from functools import wraps

from ..elements import BaseElement
from .._internal.utils import create_props, to_camel_case

param_descs = {
    "UNSAFE_class_name": "default",
    "UNSAFE_style": "default",
    "action": "default",
    "actions": "default",
    "align": "default",
    "align_content": "default",
    "align_items": "default",
    "align_self": "default",
    "alignment": "default",
    "allows_custom_value": "default",
    "allows_non_contiguous_ranges": "default",
    "alt": "default",
    "areas": "default",
    "aria_active_descendant": "default",
    "aria_auto_complete": "default",
    "aria_controls": "default",
    "aria_described_by": "default",
    "aria_describedby": "default",
    "aria_details": "default",
    "aria_errormessage": "default",
    "aria_expanded": "default",
    "aria_has_popup": "default",
    "aria_haspopup": "default",
    "aria_label": "default",
    "aria_labelled_by": "default",
    "aria_labelledby": "default",
    "aria_pressed": "default",
    "auto_capitalize": "default",
    "auto_columns": "default",
    "auto_complete": "default",
    "auto_flow": "default",
    "auto_focus": "default",
    "auto_rows": "default",
    "back_columns": "default",
    "background_color": "default",
    "border_bottom_color": "default",
    "border_bottom_end_radius": "default",
    "border_bottom_start_radius": "default",
    "border_bottom_width": "default",
    "border_color": "default",
    "border_end_color": "default",
    "border_end_width": "default",
    "border_radius": "default",
    "border_start_color": "default",
    "border_start_width": "default",
    "border_top_color": "default",
    "border_top_end_radius": "default",
    "border_top_start_radius": "default",
    "border_top_width": "default",
    "border_width": "default",
    "border_x_color": "default",
    "border_x_width": "default",
    "border_y_color": "default",
    "border_y_width": "default",
    "bottom": "default",
    "button_label_behaviour": "default",
    "children": "default",
    "close_on_select": "default",
    "color": "default",
    "column_gap": "default",
    "column_groups": "default",
    "columns": "default",
    "container_padding": "default",
    "context_header_menu": "default",
    "context_menu": "default",
    "contextual_help": "default",
    "cross_offset": "default",
    "decrement_aria_label": "default",
    "default_input_value": "default",
    "default_open": "default",
    "default_selected": "default",
    "default_selected_key": "default",
    "default_selected_keys": "default",
    "default_value": "default",
    "density": "default",
    "description": "default",
    "description_column": "default",
    "direction": "default",
    "disabled_keys": "default",
    "disallow_empty_selection": "default",
    "element": "default",
    "element_type": "default",
    "enc_type": "default",
    "end": "default",
    "end_name": "default",
    "error_message": "default",
    "exclude_from_tab_order": "default",
    "fill_offset": "default",
    "flex": "default",
    "flex_basis": "default",
    "flex_grow": "default",
    "flex_shrink": "default",
    "form_value": "default",
    "front_columns": "default",
    "frozen_columns": "default",
    "gap": "default",
    "granularity": "default",
    "grid_area": "default",
    "grid_column": "default",
    "grid_column_end": "default",
    "grid_column_start": "default",
    "grid_row": "default",
    "grid_row_end": "default",
    "grid_row_start": "default",
    "height": "default",
    "hidden_columns": "default",
    "hide_stepper": "default",
    "hide_time_zone": "default",
    "hour_cycle": "default",
    "href": "default",
    "icon": "default",
    "icon_column": "default",
    "id": "default",
    "increment_aria_label": "default",
    "input_mode": "default",
    "input_value": "default",
    "is_disabled": "default",
    "is_emphasized": "default",
    "is_filled": "default",
    "is_hidden": "default",
    "is_indeterminate": "default",
    "is_invalid": "default",
    "is_justified": "default",
    "is_loading": "default",
    "is_open": "default",
    "is_pending": "default",
    "is_quiet": "default",
    "is_read_only": "default",
    "is_required": "default",
    "is_selected": "default",
    "is_wheel_disabled": "default",
    "justify_content": "default",
    "justify_items": "default",
    "justify_self": "default",
    "key": "default",
    "key_column": "default",
    "keyboard_activation": "default",
    "label": "default",
    "label_align": "default",
    "label_alignment": "default",
    "label_column": "default",
    "label_position": "default",
    "left": "default",
    "level": "default",
    "loading_state": "default",
    "margin": "default",
    "margin_bottom": "default",
    "margin_end": "default",
    "margin_start": "default",
    "margin_top": "default",
    "margin_x": "default",
    "margin_y": "default",
    "max_height": "default",
    "max_length": "default",
    "max_value": "default",
    "max_visible_months": "default",
    "max_width": "default",
    "menu_trigger": "default",
    "menu_width": "default",
    "method": "default",
    "min_height": "default",
    "min_length": "default",
    "min_value": "default",
    "min_width": "default",
    "name": "default",
    "necessity_indicator": "default",
    "object_fit": "default",
    "offset": "default",
    "on_action": "default",
    "on_blur": "default",
    "on_cell_double_press": "default",
    "on_cell_press": "default",
    "on_change": "default",
    "on_change_end": "default",
    "on_column_double_press": "default",
    "on_column_press": "default",
    "on_error": "default",
    "on_focus": "default",
    "on_focus_change": "default",
    "on_input_change": "default",
    "on_invalid": "default",
    "on_key_down": "default",
    "on_key_up": "default",
    "on_load": "default",
    "on_open_change": "default",
    "on_press": "default",
    "on_press_change": "default",
    "on_press_end": "default",
    "on_press_start": "default",
    "on_press_up": "default",
    "on_reset": "default",
    "on_row_double_press": "default",
    "on_row_press": "default",
    "on_selection_change": "default",
    "on_submit": "default",
    "order": "default",
    "orientation": "default",
    "overflow": "default",
    "overflow_mode": "default",
    "padding": "default",
    "padding_bottom": "default",
    "padding_end": "default",
    "padding_start": "default",
    "padding_top": "default",
    "padding_x": "default",
    "padding_y": "default",
    "page_behavior": "default",
    "pattern": "default",
    "placeholder": "default",
    "placeholder_value": "default",
    "placement": "default",
    "position": "default",
    "quick_filters": "default",
    "rel": "default",
    "render_empty_state": "default",
    "reverse": "default",
    "right": "default",
    "row_gap": "default",
    "rows": "default",
    "selected_key": "default",
    "selected_keys": "default",
    "selection_mode": "default",
    "should_flip": "default",
    "should_focus_wrap": "default",
    "should_force_leading_zeros": "default",
    "show_error_icon": "default",
    "show_format_help_text": "default",
    "show_quick_filters": "default",
    "show_search": "default",
    "show_value_label": "default",
    "size": "default",
    "slot": "default",
    "src": "default",
    "start": "default",
    "start_name": "default",
    "static_color": "default",
    "step": "default",
    "style": "default",
    "summary_icon": "default",
    "table": "default",
    "target": "default",
    "text_value": "default",
    "title": "default",
    "title_column": "default",
    "top": "default",
    "track_gradient": "default",
    "trigger": "default",
    "type": "default",
    "validation_behavior": "default",
    "validation_errors": "default",
    "validation_state": "default",
    "value": "default",
    "variant": "default",
    "width": "default",
    "wrap": "default",
    "z_index": "default",
}


def make_element(
    description: str,
    override_name: str | None = None,
    override_param_descs: dict[str, str] = {},
    override_return: str | None = None,
):
    """
    A decorator creator thats turns a function (that returns `global() of its props`) into a component.

    Args:
        description: The description of the component.
        override_name: The name of the component that will override the default (the function name in camel case).
        override_param_descs: A dictionary of prop descriptions that will override the default ones.
        override_return: The string that will override the default ("The rendered {name} component.") return value.
    """

    def decorator(f: Any):
        nonlocal override_name
        nonlocal override_return

        sig = signature(f)

        # Run here so it's run once
        if override_name is None:
            override_name = to_camel_case(f.__name__)
        if override_return is None:
            override_return = f"The rendered {override_name} component."

        @wraps(f)
        def wrapper(*args, key: str | None = None, **kwargs):
            children, props = create_props(f(*args, **kwargs))
            props["key"] = key
            return BaseElement(
                f"deephaven.ui.components.{override_name}", *children, **props
            )

        wrapper.__doc__ = f"{description}\n\nArgs:\n"
        for param_name in (param.name for param in sig.parameters.values()):
            if param_name in override_param_descs:
                wrapper.__doc__ += (
                    f"    {param_name}: {override_param_descs[param_name]}\n"
                )
            elif param_name in param_descs:
                wrapper.__doc__ += f"    {param_name}: {param_descs[param_name]}\n"
            else:
                raise ValueError(f'Docs of parameter "{param_name}" not specified.')
        wrapper.__doc__ += f"    key: A unique key for the element\n"
        wrapper.__doc__ += f"\nReturns:\n    {override_return}\n"

        return wrapper

    return decorator
