# Note this expects checkout to already be performed
name: 'Get changed plugins'
description: 'Get the list of plugins that have been modified in the current PR or push'
outputs:
  packages:
    description: 'Changed packages'
    value: ${{ steps.filter.outputs.changes }}

runs:
  using: 'composite'
  steps:
    - name: Filter paths
      uses: dorny/paths-filter@v3
      id: filter
      with:
        # On this release/ui-v0.31 branch, just disable all the other plugins from being tested since it will just be deephaven.ui updates
        filters: |
          ui:
            - plugins/ui/**
            - .github/workflows/test-*.yml
            - sphinx_ext/*
          utilities:
            - plugins/utilities/**
            - .github/workflows/test-*.yml
          packaging:
            - plugins/packaging/**
            - .github/workflows/test-*.yml
