type=script
scriptType=python
enabled=true
id=web.test
name=Plugins Test Application
file_0=express.py
file_1=matplotlib.py
file_2=ui.py
file_3=ui_render_all.py
file_4=ui_flex.py
file_5=ui_table.py
file_6=ui_panel_loading.py
file_7=ui_dialog.py
file_8=ui_markdown_code.py
file_9=ui_grid.py
file_10=ui_plotly.py
file_11=ag_grid.py