name: Build Python Package

on:
  workflow_call:
    inputs:
      package:
        description: 'Name of the package to build'
        required: true
        type: string
      js:
        description: 'Whether to build and bundle the JS package with Python'
        required: false
        type: boolean
        default: true
      artifact-name:
        description: 'Name of the artifact to upload'
        required: true
        type: string

jobs:
  build-python-package:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check JS existence
        if: ${{ inputs.js == 'true' }}
        id: check_files
        uses: andstor/file-existence-action@v3
        with:
          files: 'plugins/${{ inputs.package }}/src/js/package.json'

      - name: Setup Node
        id: setup-node
        if: ${{ inputs.js == 'true' && steps.check_files.outputs.files_exists == 'true' }}
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install npm dependencies
        if: ${{ steps.setup-node.conclusion == 'success'}}
        run: npm ci

      - name: Build npm packages
        if: ${{ steps.setup-node.conclusion == 'success'}}
        run: npm run build -- --scope "@deephaven/js-plugin-${{ inputs.package }}"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install build dependencies
        run: python -m pip install --upgrade setuptools wheel build

      - name: Build wheel
        run: python -m build --wheel --sdist plugins/${{ inputs.package }}

      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: plugins/${{ inputs.package }}/dist/
          if-no-files-found: error
