name: Build JSON Plugin

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'plugins/json/**'
  push:
    branches: [ main ]
    tags: [ 'json-v*' ]

defaults:
  run:
    working-directory: 'plugins/json'

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python: ["3.9", "3.10", "3.11"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install tox
        run: pip install tox

      - name: Run tox
        run: tox

  build-dist:
    needs: test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install build dependencies
        run: python -m pip install --upgrade setuptools wheel build

      - name: Build wheel
        run: python -m build

      - name: Upload dist
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: 'plugins/json/dist/'
          if-no-files-found: error

      - name: Publish package
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/json-v')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_JSON_TOKEN }}
          packages-dir: 'plugins/json/dist/'
