name: Build Plotly Express Plugin

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'plugins/plotly-express/**'
  push:
    branches: [ main ]
    tags: [ 'plotly-express-v*' ]

defaults:
  run:
    working-directory: 'plugins/plotly-express'

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python: [ "3.8", "3.9", "3.10", "3.11" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install tox
        run: pip install tox

      - name: Run tox
        run: tox -e py

  build-dist:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install build dependencies
        run: python -m pip install --upgrade setuptools wheel build

      - name: Build wheel
        run: python -m build

      - name: Upload dist
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: 'plugins/plotly-express/dist/'
          if-no-files-found: error

      - name: Publish package
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/plotly-express-v')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_PLOTLY_EXPRESS_TOKEN }}
          packages-dir: 'plugins/plotly-express/dist/'
