name: 'Conventional PR'

on:
  pull_request_target:
    paths:
      - '**/docs/**/*.md'

jobs:
  add-reviewer:
    if: github.event.pull_request.draft == false
    permissions:
      pull-requests: write
    runs-on: ubuntu-22.04

    steps:
      - name: Add reviewers
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              reviewers: ['margaretkennedy']
            })
