name: Make Docs

on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  build-plugin:
    if: ${{ inputs.package }} == 'plotly-express'
    uses: ./.github/workflows/build-python-package.yml
    with:
      package: ${{ inputs.package }}

  make-docs:
    needs: build-plugin
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download dist
        uses: actions/download-artifact@v3
        with:
          name: dist-${{ inputs.package }}
          path: plugins/${{ inputs.package }}/dist/

      - name: Install requirements
        run: pip install -r plugins/${{ inputs.package }}/requirements.txt

      - name: Install wheel
        run: pip install plugins/${{ inputs.package }}/dist/*.whl

      - name: Run make_docs.py
        run: python plugins/${{ inputs.package }}/make_docs.py

      - name: Upload docs
        uses: actions/upload-artifact@v3
        with:
          name: docs-plotly-express-${{ inputs.version }}
          path: plugins/${{ inputs.package }}/docs/build/markdown/
          if-no-files-found: error
