name: Make Docs

on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  make-docs:
    if: ${{ github.event.inputs.package }} == 'plotly-express'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Python Package
        uses: ./.github/workflows/build-python-package.yml
        with:
          package: ${{ github.event.inputs.package }}

      - name: Download dist
        uses: actions/download-artifact@v3
        with:
          name: dist-${{ inputs.package }}
          path: plugins/${{ github.event.inputs.package }}/dist/

      - name: Install requirements
        run: pip install -r plugins/${{ github.event.inputs.package }}/requirements.txt

      - name: Install wheel
        run: pip install plugins/${{ github.event.inputs.package }}/dist/*.whl

      - name: Run make_docs.py
        run: python plugins/${{ github.event.inputs.package }}/make_docs.py

      - name: Upload docs
        uses: actions/upload-artifact@v3
        with:
          name: website/deephaven/deephaven-plugins/plotly-express/${{ github.event.inputs.version }}
          path: plugins/${{ github.event.inputs.package }}/docs/build/markdown/
          if-no-files-found: error
