name: Publish Docs

on:
  workflow_run:
    workflows: ['Test Modified Plugin'] # Only runs on top level workflows, not reusable workflows called from another run
    types:
      - completed

jobs:
  get-docs-packages:
    runs-on: ubuntu-24.04
    outputs:
      packages: ${{ steps.packages.outputs.packages }}
    steps:
      - name: Get docs to publish
        uses: actions/github-script@v7
        id: packages
        with:
          script: |
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{ github.event.workflow_run.id }}
            });
            const versions = artifacts.data.artifacts.filter(artifact => artifact.name.startsWith('docs-build-'));
            return versions.map(artifact => artifact.name.replace('docs-build-', ''));
      # - name: Download docs
      #   uses: actions/download-artifact@v4
      #   with:
      #     path: docs-build
      #     pattern: docs-build-*
      #     merge-multiple: true # Makes the docs-build directory ready to upload directly to GCP
      #     run-id: ${{ github.event.workflow_run.id }}
      #     github-token: ${{ github.token }}

      # Outputs an array of $PACKAGE_NAME/$VERSION/ directories
      # - name: Find packages
      #   id: packages
      #   run: echo "packages=$(ls -d docs-build/*/*/ | jq --raw-input --slurp --compact-output 'split("\n")[:-1]') | map(ltrimstr("docs-build/"))" >> ${GITHUB_OUTPUT}

  publish-docs:
    needs: get-docs-packages
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        package: ${{fromJson(needs.get-docs-packages.outputs.packages)}}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: docs-build-${{ matrix.package }}
          path: docs-build

      - name: Sync ${{ matrix.package }} to ${{ github.event.workflow_run.event == 'push' && 'prod' || 'preview' }}
        if: ${{ github.event.workflow_run.event == 'push' }}
        uses: deephaven/salmon-sync@v1
        with:
          source: docs-build/${{ matrix.package }}
          destination: deephaven/deephaven-plugins/${{ matrix.package }}
          project_number: ${{ secrets.DOCS_GOOGLE_CLOUD_PROJECT_NUMBER}}
          bucket: ${{ github.event.workflow_run.event == 'push' && vars.DOCS_GOOGLE_CLOUD_BUCKET || vars.DOC_PREVIEW_BUCKET }}
          credentials: ${{ secrets.DOCS_GOOGLE_CLOUD_CREDENTIALS }}
