name: Publish Prod Docs

on:
  workflow_run:
    workflows: ['Test Modified Plugin'] # Only runs on top level workflows, not reusable workflows called from another run
    types:
      - completed
    branches:
      - main
      - 'release/**'

jobs:
  get-docs-packages:
    if: ${{ github.event.workflow_run.event == 'push' }}
    runs-on: ubuntu-24.04
    outputs:
      packages: ${{ steps.packages.outputs.result }}
    steps:
      - name: Get docs to publish
        uses: actions/github-script@v7
        id: packages
        with:
          script: |
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{ github.event.workflow_run.id }}
            });
            const versions = artifacts.data.artifacts.filter(artifact => artifact.name.startsWith('docs-build-'));
            const packages = versions.map(artifact => artifact.name.replace('docs-build-', ''))
            return packages;

  publish-docs:
    needs: get-docs-packages
    if: ${{ needs.get-docs-packages.outputs.packages != '[]' && needs.get-docs-packages.outputs.packages != '' }}
    runs-on: ubuntu-24.04
    permissions:
      id-token: write # Auth to AWS with OIDC
      pull-requests: write # Add comment
      actions: read # Download artifact
    strategy:
      fail-fast: false
      matrix:
        package: ${{fromJson(needs.get-docs-packages.outputs.packages)}}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: docs-build-${{ matrix.package }}
          path: docs-build
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}

      # Extract the package and version from the artifact directories
      # Each artifact should only contain 1 package and 1 version as the first 2 directories
      - name: Extract package and version
        run: |
          echo "package=$(ls docs-build)" >> $GITHUB_ENV
          echo "version=$(ls docs-build/*)" >> $GITHUB_ENV

      - name: Sync ${{ env.package }}/${{ env.version }} to prod
        uses: deephaven/salmon-sync@v1
        with:
          source: docs-build/${{ env.package }}/${{ env.version }}/
          destination: deephaven/deephaven-plugins/${{ env.package }}/${{ env.version }}/
          production: true
          temporary: false
          aws-role: ${{ vars.DOCS_AWS_ROLE }}
