name: 'Add docs reviewers'

on:
  # Needs to be pull_request_target for pull-request write permission
  pull_request_target:
    paths:
      - '**/docs/**/*.md'
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  add-docs-reviewers:
    if: github.event.pull_request.draft == false
    permissions:
      pull-requests: write
    runs-on: ubuntu-22.04

    steps:
      - name: Add docs reviewers
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              reviewers: ['margaretkennedy']
            })
