name: Tag Python Package

on:
  push:
    branches: [ main ]
    tags:
      - 'plotly-express-v*'
      - 'plotly-v*'
      - 'matplotlib-v*'
      - 'json-v*'

jobs:
  build-dist:
    runs-on: ubuntu-22.04
    steps:
      - name: Publish plotly express package
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/plotly-express-v')
        steps:
          - uses: release-python-package.yml@main
            with:
              package: plotly-express
              token: ${{ secrets.PYPI_PLOTLY_EXPRESS_TOKEN }}

      - name: Publish plotly package
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/plotly-v')
        steps:
          - uses: release-python-package.yml@main
            with:
              package: plotly
              token: ${{ secrets.PYPI_PLOTLY_TOKEN }}

      - name: Publish matplotlib package
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/matplotlib-v')
        steps:
          - uses: release-python-package.yml@main
            with:
              package: matplotlib
              token: ${{ secrets.PYPI_MATPLOTLIB_TOKEN }}

      - name: Publish json package
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/json-v')
        steps:
          - uses: release-python-package.yml@main
            with:
              package: json
              token: ${{ secrets.PYPI_JSON_TOKEN }}

