name: Check TypeScript types

on:
  push:
    branches:
      - main
      - 'release/**'
      - 'feature/**'
  pull_request:
    branches:
      - main
      - 'release/**'
      - 'feature/**'

jobs:
  typescript-check:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Check TypeScript types
        run: python tools/check_typescript_ci.py

